version: "3.3"
services:
  mongo:
    image: "mongo:latest"
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    network_mode: mongo_network
    volumes:
      - "$PWD/db:/data/db"

  mongo-express:
    image: "mongo-express:latest"
    container_name: mongo-express
    network_mode: mongo_network
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - "8081:8081"
